services:
  evabookshop:
    image: evabookshop
    build:
      context: .
      dockerfile: EVABookShop/Dockerfile
    ports:
      - "8080:8080"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=EXPRESS
    ports:
      - "1433:1433"

